spring:
  application:
    name: centralbank
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true